apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nginx-pv
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/logs
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard # pvs' can have class and this pv can only be bound to pvc that requesting that class
