apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-nginx-pvc
spec:
  storageClassName: standard # will be bound to the pv with same class
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
