apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-vol1
spec:
  selector:
    matchLabels:
      app: test-vol1
  template:
    metadata:
      name: test-vol1-pod
      labels:
        app: test-vol1
    spec:
      containers:
      - name: alpine1
        image: alpine
        command: ["sh", "-c", "touch /test-dir/sample.txt; sleep 3600"]
        volumeMounts:
        - name: test-vol
          mountPath: /test-dir
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: alpine2
        image: alpine
        volumeMounts:
        - name: test-vol
          mountPath: /checking-dir
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: test-vol
        emptyDir: {}