apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: node-app
spec:
  replicas: 8
  selectors:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
  containers:
  - name: node-app
    image: sreeram91/versionapp:v1
    ports:
    - containerPort: 3004