apiVersion: v1
kind: Pod
metadata: 
  name: init-container-demo
spec:
  containers:
  - name: nginx-as-primary
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: alpine-as-secondary
    image: alpine
    command:
    - sh
    - "-c"
    - |
      mkdir -p init-cont && touch /init-cont/index.html && echo "Hello.. this trasfered from init-cont" > /init-cont/index.html
      sleep 30
    volumeMounts:
    - name: myvol
      mountPath: /init-cont
  volumes:
  - name: myvol
    emptyDir: {}
    
    
