apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec: #under spec goes all the replicationController details such as how many replicas, selector to match the labels of container.
  replicas: 3
  selector: 
    app: nginx
  template:  #under template goes all the container details and specifications
    metadata:
      name: nginx-rc
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
  
