apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-singlepointentry
  labels:
    app: rs-nginx
spec:
  replicas: 2
  selector:
    matchLabels: 
      tier: nginx-frontend
  template:
    metadata:
      labels:
        tier: nginx-frontend
    spec:
      containers:
      - name: nginx-rs
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rs-singlepointentry-service
  labels:
    app: nginx-frontend
spec:
  #type: LoadBalancer
  selector:
    tier: nginx-frontend
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP

    
        
        
