apiVersion: v1
kind: Pod
metadata:
  name: busybox-to-leverage-db-connection
  labels:
    name: busybox-app
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    command: ["/bin/sh", "-c", "echo $DB_USERNAME && echo $DB_PASSWORD && sleep 3600"]
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: db-username
          name: db-credentials
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: db-password
          name: db-credentials