# make use of hostPath if you want to share the location from your container to the VM (node assigned). This has some restrictions too.
apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    name: mynginx-app
spec:
  containers:
  - name: mynginx-app
    image: nginx:latest
    volumeMounts:
    - name: mynginx-vol
      mountPath: /var/log/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
  volumes:
  - name: mynginx-vol
    hostPath: 
      path: /tmp/logs # path on the host system where you want to share the data (node on which this pod will be scheduled)
      type: Directory # this field is optional