---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: affinity-example-app
  template:
    metadata:
      name: affinity-example-pod
      labels:
        app: affinity-example-app
    spec:
      affinity:
        nodeAffinity: # deciding on which node the pod has to be scheduled based on a condition given
          preferredDuringSchedulingIgnoredDuringExecution: # this will make the pod scheduled to any node even if the condition is not met
            - weight: 80 # 80% weightage is given to the node whose label in zone=east
              preference:
                matchExpressions:
                  - key: zone
                    operator: In # means => key with a value "in" the set of values
                    values:
                      - east
            - weight: 20 # 20% weightage is given to the node whose label is env=prod
              preference:
                matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - prod
      containers:
        - name: nginx-app
          image: nginx:latest
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          ports:
            - containerPort: 80
