apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-updates
  labels:
    app: simple-node-app
spec:
  replicas: 5
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: simple-node-app
  template:
    metadata:
      labels:
        app: simple-node-app
    spec:
      containers:
      - name: rollingupdatesx86-nodeapp
        image: sreeram91/versionappx86:v1
        ports:
        - containerPort: 3004

---
apiVersion: v1
kind: Service
metadata:
  name: rolling-updates-service
spec:
  type: NodePort
  selector:
    app: simple-node-app
  ports:
  - port: 3050
    targetPort: 3004
    nodePort: 30714
    protocol: TCP
