apiVersion: v1
kind: Pod
metadata:
  name: rp-demo
  labels:
    app: rp-nginx-app
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 90
      initialDelaySeconds: 5
      periodSeconds: 5