apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deployment
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: db-connection-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-connection-secret
        ports:
        - containerPort: 5432