apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      name: redis-app-pod
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis
        image: redis:latest
        volumeMounts:
        - name: vol-secret
          mountPath: /apps/secrets
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 6379
      volumes:
      - name: vol-secret
        secret:
          secretName: redis-secret