apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  backoffLimit: 4 # will try to run the job 4 times in case of any failure before marking the job as failed.
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
        - "bin/bash"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1 0; do echo $i; done"
      restartPolicy: Never
