apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-name
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      nodeName: node-1
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
