apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector-deployment
spec:
  selector:
    matchLabels:
      app: node-selector-app
  template:
    metadata:
      name: node-selector-pod
      labels:
        app: node-selector-app
    spec:
      nodeSelector:
        env: prod
      containers:
      - name: nginx-app-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
