apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      nodeName: node-1
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
      - name: alpine
        image: alpine
        command:
        - "/bin/sh"
        - "-c"
        - "mkdir -p /nginx-files && echo 'hello from nginx app' > /nginx-files/sample.html"
        volumeMounts:
        - name: nginx-volume
          mountPath: /nginx-files
      volumes:
      - name: nginx-volume
        emptyDir: {}
