apiVersion: v1
kind: Deployment
metadata:
  - name: node-name-ex2
spec:
  selector:
    matchLabels:
      tier: custom-nginx
  template:
    metadata:
      name: custom-nginx
      labels:
        tier: custom-nginx
    spec:
      nodeName: node-2
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMount:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: alpine
        image: alpine
        command:
        - sh
        - "-c"
        - "mkdir -p /nginx-files && echo 'Hello from NGINX!' > /nginx-files/sample.html"
        volumeMount:
        - name: nginx-volume
          mountPath: /nginx-file/sample.html
      volumes:
      - name: nginx-volume
        emptyDir: {}