apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-name-ex2
spec:
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: alpine 
        image: alpine
        command:
        - "bin/sh"
        - "-c"
        - "mkdir -p /nginx-files && echo Hello there!!' > /nginx-files/sample.html"
        volumeMounts:
        - name: nginx-vol
          mountPath: /nginx-files
      volumes:
      - name: nginx-vol
        emptyDir: {}