apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  labels:
    name: node-selector-pod
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 3600
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
