apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingresscontroller-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingresscontroller-app-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 5
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 40

